name = "wawp"
main = "src/worker/index.ts"
compatibility_date = "2024-01-01"

[vars]
DATABASE_URL = "postgresql://neondb_owner:npg_zQbVCKW9hwf4@ep-square-lab-ajlk0dwj-pooler.c-3.us-east-2.aws.neon.tech/neondb?channel_binding=require&sslmode=require"